### ISSUE TITLE
Many new Perl dependencies in version 2.0.3

### ISSUE THREAD

**Issue by ivulfson** [mnunberg/perl-Couchbase-Client#37]
Looks like version 2.0.3 added many new Perl dependencies.  Some may be justified, some could use a second look, IMHO.

* `JSON::MaybeXS` dependency was added, which also adds dependencies on `JSON::PP` and `Test::Without::Module`.  Is it really necessary, since `JSON` will use `JSON::XS` if it's installed, and fall back to `JSON` if it's not?

* The `Data::Printer` dependency also adds dependencies on:

```
Clone::PP
File::HomeDir
Package::Stash
Sort::Naturally
Term::ANSIColor
```
I didn't check any of the sub-dependencies of the above modules, but there may be more.  `Data::Printer` is great for testing, but using it makes `perl-Couchbase` library dependent on it, when building an RPM.  This is also probably not necessary when deploying `perl-Couchbase` to a production environment.  You could replace `Data::Printer` with the standard `Data::Dumper`:

```perl
use Data::Dumper;
sub p {
    print Dumper(\@_);
}
```

* `Carp::Always` (in `eg/sample.pl`) can be simply implemented with something like (if at all?):

```perl
use Carp;
$SIG{__WARN__} = sub { Carp::cluck @_; };
$SIG{__DIE__}  = sub { Carp::confess @_; };
```

* `eg/durability.pl` uses `Data::Printer`, but I don't see it actually being used.

* `lib/Couchbase/Document.pm` won't compile on RHEL6 64-bit, with `Class::XSAccessor::Array` 1.19:

```bash
$ perl -cw lib/Couchbase/Document.pm
Cannot replace existing subroutine '_cas' in package 'Couchbase::Document' with an XS implementation. If you wish to force a replacement, add the 'replace => 1' parameter to the arguments of 'use Class::XSAccessor::Array'. at lib/Couchbase/Document.pm line 14
BEGIN failed--compilation aborted at lib/Couchbase/Document.pm line 21.
```

Adding `replace => 1` makes it throw a bunch of warnings:

```
$ perl -cw lib/Couchbase/Document.pm
Subroutine is_ok redefined at lib/Couchbase/Document.pm line 24.
Subroutine is_not_found redefined at lib/Couchbase/Document.pm line 31.
Subroutine is_cas_mismatch redefined at lib/Couchbase/Document.pm line 32.
Subroutine is_already_exists redefined at lib/Couchbase/Document.pm line 33.
Subroutine new redefined at lib/Couchbase/Document.pm line 34.
Subroutine errstr redefined at lib/Couchbase/Document.pm line 56.
Subroutine copy redefined at lib/Couchbase/Document.pm line 66.
Subroutine format redefined at lib/Couchbase/Document.pm line 83.
Subroutine as_hash redefined at lib/Couchbase/Document.pm line 105.
Subroutine _data_printer redefined at lib/Couchbase/Document.pm line 119.
lib/Couchbase/Document.pm syntax OK
```

**Comment by mnunberg** [comment]
Hrm. I was not aware of any dependencies on `Data::Printer` -- if there are, it is likely due to debugging (and I guess can be fixed by removing the compile-time `p $foo` to `p($foo)` -- however that's still not a solution.

The same goes for `Carp::Always`, which shouldn't be a direct dependency.

If you know of a nice way to "sandbox-test" stuff like this, I'm all ears :)

**Comment by mnunberg** [comment]
Regarding the replacement of `JSON` with `JSON::MaybeXS` is that JSON will not by default try to use one of the XS modules. This makes the client abysmally slow -- and performance diffs are often difficult to track down. I suppose I can make something simple which creates a JSON object, otherwise _warning_ if it can't find a qualified XS module.

**Comment by ivulfson** [comment]
I would highly recommend replacing `Data::Printer` with the standard `Data::Dumper`.  This makes it more portable, albeit yes, less pretty.  Neither `Data::Printer` nor `Carp::Always` are dependencies in the library (except for `Couchbase::Document`, which uses `Data::Printer` for some reason, as opposed to other Couchbase:: classes that use `Data::Dumper`).  But since you have the `eg` files in the `MANIFEST`, that makes them dependencies when you try to make an RPM.


Regarding `JSON`:
From JSON POD (https://metacpan.org/pod/JSON):
```
This module converts Perl data structures to JSON and vice versa using either JSON::XS or JSON::PP.

JSON::XS is the fastest and most proper JSON module on CPAN which must be compiled and installed in your environment. JSON::PP is a pure-Perl module which is bundled in this distribution and has a strong compatibility to JSON::XS.

This module try to use JSON::XS by default and fail to it, use JSON::PP instead. So its features completely depend on JSON::XS or JSON::PP.
```
I guess you could explicitly require `JSON::XS`, and `use JSON::XS` everywhere you currently `use JSON::MaybeXS`.  This would make it more portable, for sure.

**Comment by mnunberg** [comment]
Maybe you can patch the RPM to _not_ scan the `eg` directory? It would seem like a bug in your RPM generator to declare a dependency on something that's `eg`. `JSON::MaybeXS` however acts in an interesting way, in that it _depends_ on an XS module if a C compiler is available, and otherwise falls back to using the `::PP` variant. This is different than `JSON` which simply tries to make this decision at runtime.

Let's see what I can do quickly as far as the JSON module goes (since that's something which is a core dependency). I'll work on the `eg` directory later, but I still think it's something that's broken in whatever is generating the RPM (the stuff in `eg` is equivalent to documentation).

**Comment by ivulfson** [comment]
I can exclude `eg` from the MANIFEST, yes, but `lib/Couchbase/Document.pm` uses `Data::Printer` also. :)  I can remove it from there as well, I guess:

```
$ git diff lib/Couchbase/Document.pm
diff --git a/lib/Couchbase/Document.pm b/lib/Couchbase/Document.pm
index f1973cd..d997c25 100644
--- a/lib/Couchbase/Document.pm
+++ b/lib/Couchbase/Document.pm
@@ -6,6 +6,7 @@ use Couchbase::Core;
 use Couchbase::Constants;
 use Couchbase::_GlueConstants;
 use Couchbase;
+use Data::Dumper;
 use base qw(Exporter);
 
 our @EXPORT = (qw(COUCHBASE_FMT_JSON COUCHBASE_FMT_UTF8 COUCHBASE_FMT_RAW COUCHBASE_FMT_STORABLE));
@@ -17,7 +18,8 @@ use Class::XSAccessor::Array {
         _cas => RETIDX_CAS,
         value => RETIDX_VALUE,
         errnum => RETIDX_ERRNUM,
-    }
+    },
+    replace => 1,
 };
 
 sub is_ok {
@@ -118,7 +120,7 @@ sub as_hash {
 sub _data_printer {
     my $self = shift;
     my $r = bless $self->as_hash, ref($self) . "::_PrettyDummy";
-    Data::Printer::p($r);
+    print Dumper($r);
 }
 
 
```
But then, I could just give you a pull request with these fixes.  Would you rather do that?

**Comment by ivulfson** [comment]
Actually, I'm not sure if `use Data::Dumper;` in `lib/Couchbase/Document.pm` is not necessary.  The `_data_printer` doesn't seem to be used anywhere?...

**Comment by ivulfson** [comment]
Anyway, let me make you a new drop, and you can take a look at what I mean.

**Comment by mnunberg** [comment]
The `_data_printer` function is used by `Data::Printer`, and thus it's used implicitly by that module, if it's loaded. Otherwise it's innocuous

```
mnunberg@csure:~/src/Couchbase-Client$ git grep Data::Printer lib/
lib/Couchbase/Document.pm:    Data::Printer::p($r);
```

If the module is loaded, the call will resolve to something; and the sub is only invoked if someone calls `p $bucket` or similar.

**Comment by mnunberg** [comment]
Try latest commit

**Comment by ivulfson** [comment]
The latest commit (f0846d0b7221bc4081fc6feddc4d722b2a9d2576) builds the RPM fine, but won't yum install:

```
Resolving Dependencies
--> Running transaction check
---> Package perl-Couchbase.x86_64 0:2.0.1-1 will be updated
---> Package perl-Couchbase.x86_64 0:2.0.3-1 will be an update
--> Processing Dependency: perl(Carp::Always) for package: perl-Couchbase-2.0.3-1.x86_64
--> Processing Dependency: perl(Data::Printer) for package: perl-Couchbase-2.0.3-1.x86_64
--> Processing Dependency: perl(JSON::MaybeXS) for package: perl-Couchbase-2.0.3-1.x86_64
--> Finished Dependency Resolution
Error: Package: perl-Couchbase-2.0.3-1.x86_64 (/perl-Couchbase-2.0.3-1.x86_64)
           Requires: perl(Data::Printer)
Error: Package: perl-Couchbase-2.0.3-1.x86_64 (/perl-Couchbase-2.0.3-1.x86_64)
           Requires: perl(Carp::Always)
Error: Package: perl-Couchbase-2.0.3-1.x86_64 (/perl-Couchbase-2.0.3-1.x86_64)
           Requires: perl(JSON::MaybeXS)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

See my pull request #38

**Comment by mnunberg** [comment]
So:

1. Nothing in `lib/` does `use Data::Printer`, and as such should not be a dep. If your cpan2rpm module simply checks for any `::` and automatically decides that it needs to have a dependency on such a module, then it needs to be fixed (what about dynamically generated module names? those have globs but aren't in any file!)
2. `Carp::Always` might not belong in an example, but again only appears inside tests. While the tests are technically in `lib`, this is more of a cosmetic design - and something I might change eventually - in any event, excluding the `lib/Couchbase/Test/*` directory might be a better option. Carp::Always is helpful in tests. I suppose doing something like:

`eval { require Carp::Always; Carp::Always->import(); }` works just as well :)

**Comment by ivulfson** [comment]
Oh, good.  Added Carp::Always back in, made another push.

**Comment by ivulfson** [comment]
Fixing cpan2rpm is arguably outside the scope of this library, no? :)

**Comment by mnunberg** [comment]
Can you tell me how to install cpan2rpm to see what I can do? There might be some way to trick it

**Comment by ivulfson** [comment]
cpan2rpm has --no-requires command line argument, and I'm trying to see if it works.  So far - no go.

```
git clone https://github.com/ekkis/cpan2rpm
cd cpan2rpm
git log > Changes
./cpan2rpm --mk-rpm-dirs=~/rpm
./cpan2rpm --no-sign --no-prfx --source cpan2rpm-2.031.tar.gz .
```

The resulting file will be in ~/rpm/RPMS/noarch/cpan2rpm-2.031-1.noarch.rpm

**Comment by ivulfson** [comment]
AAAAAAAAAAAAAA!!!!  IT WORKS!!!!!!

```
cpan2rpm --no-sign --make-no-test --no-requires 'perl(Data::Printer),perl(Carp::Always)' --source Couchbase-2.0.3.tar.gz . 
sudo yum install ~/rpm/RPMS/x86_64/perl-Couchbase-2.0.3-1.x86_64.rpm
```

**Comment by mnunberg** [comment]
I get a really odd error when trying to build:

```
ERROR   0001: file '/usr/local/lib64/perl5/auto/Couchbase/Couchbase.so' contains a standard rpath '/usr/lib64' in [/usr/lib64]
error: Bad exit status from /var/tmp/rpm-tmp.UlBJ4z (%install)
```

**Comment by mnunberg** [comment]
Gonna try with the `QA_RPATHS` mask..

**Comment by ivulfson** [comment]
Mark, `--no-requires 'perl(Data::Printer),perl(Carp::Always)'` actually works.  It builds the RPM, and yum installs it.  What a relief...  

Also, somehow, Couchbase::Document works just fine if you use use it, even without `replace=>1`.

I'm going to close this bug, if you don't mind, close the pull request.
