### ISSUE TITLE
Feature: getAndLock

### ISSUE THREAD

**Issue by celogeek** [mnunberg/perl-Couchbase-Client#39]
Hi,

I have seen that java version got getAndLock feature.

Is it possible to add the support ?

I need pessimistic lock, because the CAS is not safe enough (I can make it fail really easily with fork).

For now I do something like this :

```
my $lock = Couchbase::Document->new("x_lock");
$lock->format("raw");
$lock->value("mysecretlockkey");
$lock->expiry(time + 30);
while(!$cb->insert("x_lock")) {
 usleep(rand(100_000));
$lock->expiry(time + 30);
}
return  $lock
```

It works, but if couchbase has an internal method for this, I would prefer to use it.

Tell me if I can help on something.

**Comment by mnunberg** [comment]
There is a `get_and_lock` method, however I forgot to document it. Likewise there is also an `unlock` method.

See https://github.com/mnunberg/perl-Couchbase-Client/blob/master/lib/Couchbase/Test/ClientSync.pm#L270
