### ISSUE TITLE
Connection string behaviour unclear

### ISSUE THREAD

**Issue by benvanstaveren** [mnunberg/perl-Couchbase-Client#43]
I'm not sure if it's a bug or a "feature", but when specifying multiple hosts in a connection string (e.g. couchbase://foo.host,bar.host,baz.host/bucket), it doesn't seem to "do what you expect". When "foo.host" is down. Couchbase::Bucket throws a fatal error, and does not try an of the other hosts listed. This is a bit of an issue considering clusters, and such things.

**Comment by mnunberg** [comment]
This really depends on how the host is failing. There are multi-host settings and timeout settings; by default the cummulative timeout for _all_ hosts is 4 seconds, with 2 seconds per host. This is enough to try two hosts. These settings can of course be adjusted via the `config_node_timeout` and `config_total_timeout` connection string options.
